WINDOW_SIZE = 800, 800
WINDOW_WIDTH = WINDOW_SIZE[0]
WINDOW_HEIGHT = WINDOW_SIZE[1]

WINDOW_TITLE = "Diamond Rush"

WINDOW_WIDTH_MEASURED_IN_TILES = 10
WINDOW_HEIGHT_MEASURED_IN_TILES = 10

TILE_WIDTH = WINDOW_WIDTH // WINDOW_WIDTH_MEASURED_IN_TILES
TILE_HEIGHT = WINDOW_HEIGHT // WINDOW_HEIGHT_MEASURED_IN_TILES

TILE_SIZE = TILE_WIDTH, TILE_HEIGHT

